# Generated by Django 4.2.2 on 2023-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecemContruida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(default='Recém Construída', max_length=100)),
                ('nome_completo', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('documento_identidade', models.FileField(upload_to='documentacao/%Y/%m')),
                ('comprovante_residencia', models.FileField(upload_to='documentacao/%Y/%m')),
                ('irpf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_casamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('contrato_constituicao', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_simplificada_junta', models.FileField(upload_to='documentacao/%Y/%m')),
                ('relacao_faturamento', models.FileField(upload_to='documentacao/%Y/%m')),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriaPJ',
        ),
    ]
