# Generated by Django 4.2.2 on 2023-06-16 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_recemcontruida_delete_categoriapj'),
    ]

    operations = [
        migrations.AddField(
            model_name='recemcontruida',
            name='data_recebimento_documentacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
