# Generated by Django 4.2.2 on 2023-06-16 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_recemcontruida_data_recebimento_documentacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LucroReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(default='Lucro Real / Presumido', max_length=100)),
                ('nome_completo', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('documento_identidade', models.FileField(upload_to='documentacao/%Y/%m')),
                ('comprovante_residencia', models.FileField(upload_to='documentacao/%Y/%m')),
                ('irpf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_casamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('alteracao_contratual', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_simplificada', models.FileField(upload_to='documentacao/%Y/%m')),
                ('balanco_dre', models.FileField(upload_to='documentacao/%Y/%m')),
                ('faturamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('ecf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('data_recebimento_documentacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(default='MEI', max_length=100)),
                ('nome_completo', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('documento_identidade', models.FileField(upload_to='documentacao/%Y/%m')),
                ('comprovante_residencia', models.FileField(upload_to='documentacao/%Y/%m')),
                ('irpf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_casamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('requerimento_empresario', models.FileField(upload_to='documentacao/%Y/%m')),
                ('simei', models.FileField(upload_to='documentacao/%Y/%m')),
                ('data_recebimento_documentacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Simples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(default='Simples', max_length=100)),
                ('nome_completo', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('documento_identidade', models.FileField(upload_to='documentacao/%Y/%m')),
                ('comprovante_residencia', models.FileField(upload_to='documentacao/%Y/%m')),
                ('irpf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_casamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('alteracao_contratual', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_simplificada', models.FileField(upload_to='documentacao/%Y/%m')),
                ('extrato_simples', models.FileField(upload_to='documentacao/%Y/%m')),
                ('faturamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('data_recebimento_documentacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
