# Generated by Django 4.2.2 on 2023-06-16 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_lucroreal_mei_simples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(default='Associações e Sindicatos', max_length=100)),
                ('nome_completo', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('documento_identidade', models.FileField(upload_to='documentacao/%Y/%m')),
                ('comprovante_residencia', models.FileField(upload_to='documentacao/%Y/%m')),
                ('irpf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_casamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('estatuto_social', models.FileField(upload_to='documentacao/%Y/%m')),
                ('ata_constituicao', models.FileField(upload_to='documentacao/%Y/%m')),
                ('ata_eleicao', models.FileField(upload_to='documentacao/%Y/%m')),
                ('faturamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('data_recebimento_documentacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(default='Associações e Sindicatos', max_length=100)),
                ('nome_completo', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('documento_identidade', models.FileField(upload_to='documentacao/%Y/%m')),
                ('comprovante_residencia', models.FileField(upload_to='documentacao/%Y/%m')),
                ('irpf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_casamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('convencao', models.FileField(upload_to='documentacao/%Y/%m')),
                ('ata', models.FileField(upload_to='documentacao/%Y/%m')),
                ('faturamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('data_recebimento_documentacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empresa', models.CharField(default='Associações e Sindicatos', max_length=100)),
                ('nome_completo', models.CharField(max_length=250, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('documento_identidade', models.FileField(upload_to='documentacao/%Y/%m')),
                ('comprovante_residencia', models.FileField(upload_to='documentacao/%Y/%m')),
                ('irpf', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_casamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('estatudo_social', models.FileField(upload_to='documentacao/%Y/%m')),
                ('ata_fundacao', models.FileField(upload_to='documentacao/%Y/%m')),
                ('ata_eleicao', models.FileField(upload_to='documentacao/%Y/%m')),
                ('certidao_simplificada', models.FileField(upload_to='documentacao/%Y/%m')),
                ('balanco_dre', models.FileField(upload_to='documentacao/%Y/%m')),
                ('faturamento', models.FileField(upload_to='documentacao/%Y/%m')),
                ('data_recebimento_documentacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
