# Generated by Django 4.2.2 on 2023-06-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_associacao_condominio_cooperativa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecemContruida',
            new_name='RecemConstruida',
        ),
    ]
